### PR TITLE
config: add NeoFSBlockFetcher section

### LINKED ISSUE #3632: Add NeoFSBlockFetcher configuration to default networks configurations
Extend `./config/...` configurations for N3 mainnet/testnet and NeoFS mainnet/testnet with NeoFSBlockFetcher sections and appropriate containers info. Make BlockFetcher disabled by default.

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3632

### CODE REVIEW

**Review by AnnaShaleva — COMMENTED** [review]
LGTM, waiting for the data to be uploaded to NeoFS to ensure all configurations work properly.

**Comment by AnnaShaleva** [comment]
@AliceInHunterland, please update the container IDs.

**Comment by AnnaShaleva** [comment]
@AliceInHunterland, ready for review?

**Comment by AliceInHunterland** [comment]
@AnnaShaleva Let me check #3668 first?

**Comment by AnnaShaleva** [comment]
> Let me check https://github.com/nspcc-dev/neo-go/issues/3668 first?

I think that we won't change containers one more time, hence we can merge this PR and then use ready-to-use config files to check #3668. If some blocks are missing or corrupted, then we may reupload blocks to the existing containers.

**Comment by AliceInHunterland** [comment]
Let's merge this PR

**Review by AnnaShaleva — APPROVED** [review]
Good job, let's try it.

**Pull request merged**
