### PR TITLE
Add missing opcodes into the list

### PR DESCRIPTION
**Pull request by roman-khimov**
Add missing opcodes from the spec and expand PUSHBYTES* for convenience.

### CODE REVIEW

**Comment by roman-khimov** [comment]
```
pkg/vm/instructions.go:206:2: don't use ALL_CAPS in Go names; use CamelCase
pkg/vm/instructions.go:207:2: don't use ALL_CAPS in Go names; use CamelCase
pkg/vm/instructions.go:208:2: don't use ALL_CAPS in Go names; use CamelCase
pkg/vm/instructions.go:209:2: don't use ALL_CAPS in Go names; use CamelCase
pkg/vm/instructions.go:210:2: don't use ALL_CAPS in Go names; use CamelCase
Found 5 lint suggestions; failing.
```
```
        // Stack isolation                                                                                                                                                                                                                                                                                             
        CALL_I   Instruction = 0xE0
        CALL_E   Instruction = 0xE1
        CALL_ED  Instruction = 0xE2
        CALL_ET  Instruction = 0xE3
        CALL_EDT Instruction = 0xE4
```
Oh, my... So these are kinda "official" names and golint doesn't like 'em.

**Comment by fyrchik** [comment]
`DUPFROMALTSTACKBOTTOM` is also missing.
https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/OpCode.cs#L430

**Comment by roman-khimov** [comment]
> Why is DUPFROMALTSTACKBOTTOM called TAILCALL in our code?
Because it is a `TAILCALL` for 2.X and you're probably looking at the `master` branch of `neo-vm`. At the moment it's better for us to wait a little (probably not more than a month) until NEO 3 development stabilizes enough and not rush implementing it.

**Comment by roman-khimov** [comment]
I think I'll just drop `CALL_*` instructions for now (or comment 'em out), because NEO 3.0 doesn't support them (see neo-project/neo-vm#145), so they're not relevant for long-term development and they're not a top priority for 2.0 implementation also. Not that it solves the problem with linter (and I'm really annoyed by it), but at least it makes things green for now.

**Pull request merged**
