### PR TITLE
WIP revive generational GC for MPT

### PR DESCRIPTION
**Pull request by fyrchik**
For comparison with #2137 , #2095 , see also #1506 .

### CODE REVIEW

**Comment by fyrchik** [comment]
Benchmark results:
```
# no GC, master
435M    chains/testnet
________________________________________________________
Executed in   78,12 secs    fish           external
   usr time  162,86 secs    0,00 millis  162,86 secs
   sys time   13,84 secs    2,09 millis   13,84 secs

# GC, master
119M    chains/testnet
________________________________________________________
Executed in   87,24 secs    fish           external
   usr time  178,69 secs    0,00 millis  178,69 secs
   sys time   15,61 secs    1,44 millis   15,61 secs

#  no GC, PR
435M    chains/testnet
________________________________________________________
Executed in   78,60 secs    fish           external
   usr time  166,70 secs  817,00 micros  166,69 secs
   sys time   14,92 secs  159,00 micros   14,92 secs

# GC, PR
238M    chains/testnet
________________________________________________________
Executed in   93,19 secs    fish           external
   usr time  243,42 secs  760,00 micros  243,42 secs
   sys time   22,52 secs  259,00 micros   22,52 secs
```

**Comment by roman-khimov** [comment]
This PR gives a lot of `2021-09-08T17:34:26.726+0300    ERROR   error during MPT GC     {"error": "GC is already running"}` for me.

**Comment by fyrchik** [comment]
@roman-khimov Thats due-to possibly low `GenerationSpan`. 100k could be better but I should test it on a longer dump.

**Comment by roman-khimov** [comment]
Old and slow.

**Pull request closed without merging**
