### PR TITLE
Replace golint with revive

### LINKED ISSUE #2170: Replace `golint` linter with `revive` for tests and set up `revive` properly
Sometimes Linter github workflow is failing with the following error:
```
Run golangci/golangci-lint-action@v2
prepare environment
go env
Installed Go in 209ms
Requested golangci-lint 'latest', using 'v1.42.1', calculation took 253ms
Installing golangci-lint v1.42.1...
Downloading https://github.com/golangci/golangci-lint/releases/download/v1.42.1/golangci-lint-1.42.1-linux-amd64.tar.gz ...
Cache not found for input keys: golangci-lint.cache-2697-316b119768e56b6319dd28b4b4b95b42158f0773, golangci-lint.cache-2697-, golangci-lint.cache-
/usr/bin/tar xz --overwrite --warning=no-unknown-keyword -C /home/runner -f /home/runner/work/_temp/7a7c95c6-7562-4a3f-b073-af4e82bb9f7d
Installed golangci-lint into /home/runner/golangci-lint-1.42.1-linux-amd64/golangci-lint in 406ms
Prepared env in 665ms

run golangci-lint
  Running [/home/runner/golangci-lint-1.42.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  Error: File is not `gofmt`-ed with `-s` (gofmt)
  
  level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
  
  Error: issues found
  Ran golangci-lint in 103915ms
```

So we need to:
* Explicitly specify `revive` version for Linter Github workflow
* Replace `golint` with `revive` in CircleCI tests

### PR DESCRIPTION
**Pull request by fyrchik**
Close #2170 .

### CODE REVIEW

**Comment by roman-khimov** [comment]
We're still using golangci-lint 1.40.0 in CircleCI, I think it's time to update it.

**Comment by AnnaShaleva** [comment]
See also [revive GitHub action](https://github.com/marketplace/actions/revive-action), let's use it directly in our `Lint` github workflow job.

**Comment by roman-khimov** [comment]
But why? We already have it running from golangci-lint, yet another workflow/action will just duplicate the check.

**Comment by AnnaShaleva** [comment]
> yet another workflow/action will just duplicate the check.

It prints `depricated` warning before running `revive`, so I suggest to replace this action with the proper one (no need to duplicate it). But you're right, we can keep it as is.

**Comment by roman-khimov** [comment]
> It prints depricated warning before running revive

Uhm, where? I'm looking at https://github.com/nspcc-dev/neo-go/pull/2177/checks?check_run_id=3598209216 and https://app.circleci.com/pipelines/github/nspcc-dev/neo-go/7117/workflows/1bd14e31-f9b4-4b25-9ac4-c5acf4f0a928/jobs/49624, both seem to be fine. golangci-lint is very convenient as an umbrella for a set of linters, so I'd prefer running revive from it instead of having a separate action/workflow/make target.

**Comment by AnnaShaleva** [comment]
It was here https://github.com/nspcc-dev/neo-go/runs/3584794962?check_suite_focus=true#step:3:76, but it seemed to be OK now.

**Review by roman-khimov — APPROVED** [review]

**Review by AnnaShaleva — APPROVED** [review]

**Pull request merged**
