### PR TITLE
Fix null handling in manifest

### LINKED ISSUE #3522: Testnet state mismatch at 4368840
## Current Behavior
State mismatch.
```
at 0: 62fd8ff9b0543aea352257db5b00bbb01d1bc0d2cc665e1f24cf5de0d16ebc7b vs 62fd8ff9b0543aea352257db5b00bbb01d1bc0d2cc665e1f24cf5de0d16ebc7b
at 4368887: 2ee5b61a18369fbde6a4d1d046f81f993edaa40ab90c8c3176a20aa80d940083 vs 43e7a72644ab96966c714f46f4237b9285b45b1cd11e3eec817f7213e7e56935
at 2184443: 1dfe45a89a0610483bc3d46590bdb35c395b82a908f8e5b83bc5c455db9b3635 vs 1dfe45a89a0610483bc3d46590bdb35c395b82a908f8e5b83bc5c455db9b3635
at 3276665: 4502e11d71d6e426242340d87f98a5019faf4b8f13601258f1e728a0947e46ac vs 4502e11d71d6e426242340d87f98a5019faf4b8f13601258f1e728a0947e46ac
at 3822776: d97ffacc9d4fc177b100671dfe757e76ebc3d07efbcaee9b3fc827cca7393c9a vs d97ffacc9d4fc177b100671dfe757e76ebc3d07efbcaee9b3fc827cca7393c9a
at 4095831: ec1cd852023cc2414af0f2bfa267332fa122d5845dbd912e0d32d2953c7208ae vs ec1cd852023cc2414af0f2bfa267332fa122d5845dbd912e0d32d2953c7208ae
at 4232359: a5b55d73d1c8d6499c6ed635b05836553563eb8dbc9e9c76e4ee75510f2de5b6 vs a5b55d73d1c8d6499c6ed635b05836553563eb8dbc9e9c76e4ee75510f2de5b6
at 4300623: dcdedf2d1bb2c10bbba53c48fb8cc5888fd9d2932e491d140719b50acbf20e79 vs dcdedf2d1bb2c10bbba53c48fb8cc5888fd9d2932e491d140719b50acbf20e79
at 4334755: 7fe48b452062396e3d75cde55492cecdb5f341b5fe174e70a1c5732d0105b93f vs 7fe48b452062396e3d75cde55492cecdb5f341b5fe174e70a1c5732d0105b93f
at 4351821: 20904b55a18074c46fabf2f14c6fc21c67f061d94cd888c58006f0d63b52471f vs 20904b55a18074c46fabf2f14c6fc21c67f061d94cd888c58006f0d63b52471f
at 4360354: 5146fa9f5a8ee7ccf3db1bb538ee8a0ddc04f185035f29694f1525278c272846 vs 5146fa9f5a8ee7ccf3db1bb538ee8a0ddc04f185035f29694f1525278c272846
at 4364620: d9652495d1f4a4836d3e2e89430296d58c5435678feed6215fb21eb9599aebd6 vs d9652495d1f4a4836d3e2e89430296d58c5435678feed6215fb21eb9599aebd6
at 4366753: 8977de326572b8c0ec2f79105c8a5062fe192a1fcbefae79f256377117835bd6 vs 8977de326572b8c0ec2f79105c8a5062fe192a1fcbefae79f256377117835bd6
at 4367820: f79bbf24acacdb297e52b391d1917e06abbdce0318a3ffedb37f06146ace86ad vs f79bbf24acacdb297e52b391d1917e06abbdce0318a3ffedb37f06146ace86ad
at 4368353: 9951b887ce50f6ee5ed5fa7f426362a6ea79c153df449e10a33796582550eced vs 9951b887ce50f6ee5ed5fa7f426362a6ea79c153df449e10a33796582550eced
at 4368620: 0f0fa439a922f76f956569c3642943f9f7432c828f3b14b9069db5704450c441 vs 0f0fa439a922f76f956569c3642943f9f7432c828f3b14b9069db5704450c441
at 4368753: 0e295fa0d65131cfb108e0923732d5708eb760dfc9a18f884b692ad6e03adc63 vs 0e295fa0d65131cfb108e0923732d5708eb760dfc9a18f884b692ad6e03adc63
at 4368820: e845a106d02f8ad83a06790c327cbb0e87445eb52c96c3de5a950ee6c13a8cff vs e845a106d02f8ad83a06790c327cbb0e87445eb52c96c3de5a950ee6c13a8cff
at 4368853: 826ab9037ed9d67b48b72c9a129ad2ca53ea38e5674da529cb848487082d1821 vs 30ed42e71c530efae6df0f8715acc1400d90853400999bd318d443856c49bba5
at 4368836: 571d00bb826c3bdd0bbfbe3f728122dd65620f05c0d032b89407cab16d0cbc5a vs 571d00bb826c3bdd0bbfbe3f728122dd65620f05c0d032b89407cab16d0cbc5a
at 4368844: 3677f1240087f0524e00c69ec5fbb1a003add1e75631b92593149cf56ee216b7 vs c0040043762e05c85020396aef6cd9f33ad2058b7a504fb2c4eb916e5b59a3ee
at 4368840: 245c8906e8b0e5d4360cc16a70e72e02df6ed1ca04755c5c9391aaf7a39fe6ca vs a7763089b954e4cb06161b593fcee1f719078ce39a1fdc934ec895d116161dc8
at 4368838: 828889ed0fa55aee8db1dd1f72873f173208c788484d3681a297db43bb23b10c vs 828889ed0fa55aee8db1dd1f72873f173208c788484d3681a297db43bb23b10c
at 4368839: a2172180fd1c6aa5f8534c389abce1a7ae339549dd003d1bff60e817ba95b9d5 vs a2172180fd1c6aa5f8534c389abce1a7ae339549dd003d1bff60e817ba95b9d5
state differs at 4368840, block 9dee58955691e110a7728d75fd80754bafa6ada20232c1f55a8087b4ff155793
block 9dee58955691e110a7728d75fd80754bafa6ada20232c1f55a8087b4ff155793:
--- https://rpc.t5.n3.nspcc.ru:20331
+++ http://seed4t5.neo.org:20332
@@ -1,2 +1,2 @@
-(*result.ApplicationLog)(0xc0002a1b40)({
+(*result.ApplicationLog)(0xc000169c40)({
  Container: (util.Uint256) (len=32 cap=32) 935715ffb487805af5c13202a2ada6af4b7580fd758d72a710e191569558ee9d,
@@ -14,3 +14,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc000294c00)(Array)
+     Item: (*stackitem.Array)(0xc0001af5c0)(Array)
     },
@@ -19,3 +19,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc000294f60)(Array)
+     Item: (*stackitem.Array)(0xc0001af800)(Array)
     }
@@ -34,3 +34,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0xc000295200)(Array)
+     Item: (*stackitem.Array)(0xc0001afaa0)(Array)
     }

transaction 6463d87dc0a5c62716c109279c7ae9edbc40bfd0f2d63e17e6302e156cfce5a5:
--- https://rpc.t5.n3.nspcc.ru:20331
+++ http://seed4t5.neo.org:20332
@@ -1,2 +1,2 @@
-(*result.ApplicationLog)(0xc0002a1dc0)({
+(*result.ApplicationLog)(0xc000169dc0)({
  Container: (util.Uint256) (len=32 cap=32) a5e5fc6c152e30e6173ed6f2d0bf40bcede97a9c2709c11627c6a5c07dd86364,
@@ -6,15 +6,9 @@
    Trigger: (trigger.Type) Application,
-   VMState: (vmstate.State) HALT,
-   GasConsumed: (int64) 1000098004,
-   Stack: ([]stackitem.Item) (len=1 cap=1) {
-    (*stackitem.Array)(0xc00053a2d0)(Array)
+   VMState: (vmstate.State) FAULT,
+   GasConsumed: (int64) 1000035859,
+   Stack: ([]stackitem.Item) {
    },
-   Events: ([]state.NotificationEvent) (len=1 cap=1) {
-    (state.NotificationEvent) {
-     ScriptHash: (util.Uint160) (len=20 cap=20) fda3fa4346ea532a258fc497ddaddb6437c9fdff,
-     Name: (string) (len=6) "Deploy",
-     Item: (*stackitem.Array)(0xc0002956e0)(Array)
-    }
+   Events: ([]state.NotificationEvent) {
    },
-   FaultException: (string) ""
+   FaultException: (string) (len=42) "Value cannot be null. (Parameter 'source')"
   }

different state found
exit status 1
```
## Expected Behavior
State match.

## Possible Solution
Fix the damn thing.

## Steps to Reproduce
Testnet.

## Context
Testnet!

## Regression
No.

## Your Environment
* Version of the product used: 0.106.2
* Server setup and configuration files used:
* Operating System and version (`uname -a`):

### PR DESCRIPTION
**Pull request by roman-khimov**
Fix #3522.

### CODE REVIEW

**Comment by roman-khimov** [comment]
The fix is confirmed for testnet up to 4372513.

**Comment by roman-khimov** [comment]
Mainnet is OK up to 5759367.

**Comment by roman-khimov** [comment]
NeoFS mainnet is OK up to 6080412.

**Comment by roman-khimov** [comment]
NeoFS testnet is OK up to 3967861.

**Review by AliceInHunterland — APPROVED** [review]

**Review by AnnaShaleva — COMMENTED** [review]
LGTM with a tiny adjustment: https://github.com/nspcc-dev/neo-go/pull/3544.

**Pull request merged**
