### PR TITLE
Added Makefile

### PR DESCRIPTION
**Pull request by anthdm**
Added a Makefile for building, running and testing convenience.

### CODE REVIEW

**Comment by volekerb** [comment]
LGTM

**Comment by roman-khimov** [comment]
Maybe it would be useful to have `GO111MODULE` export in the `Makefile`?

**Comment by anthdm** [comment]
> Maybe it would be useful to have `GO111MODULE` export in the `Makefile`?

Isn't that default `ON` in 1.12?

**Comment by roman-khimov** [comment]
> Isn't that default ON in 1.12?

Not sure about that, but we do support 1.11 anyway and our Travis/CircleCI configs both have it explicitly set.

**Comment by roman-khimov** [comment]
`dev` is gone, so this is irrelevant now.

**Pull request closed without merging**
