### PR TITLE
vm: remove FIXME comments from vm

### PR DESCRIPTION
**Pull request by fyrchik**
- change `SUBSTR` opcode
- change `Boolean`/`Integer` to `ByteArray` conversion
- update json tests to NEO3 version
- use 4-byte ID in `SYSCALL` instruction

### CODE REVIEW

**Comment by roman-khimov** [comment]
Hmm, why I don't see #477 mentioned anywhere in this bug?

**Comment by roman-khimov** [comment]
Can we use some older commit in 2c6c7f5daaae025d1797d76aec00a6d00fc1ac3c that our VM would be compatible with?

**Comment by roman-khimov** [comment]
It'd be especially nice if we're to comply with at least with preview1 of NEO 3 or something around that.

**Comment by roman-khimov** [comment]
Looks good otherwise.

**Comment by fyrchik** [comment]
@roman-khimov I don't think it's worth the effort: SUBSTR changes occured at cfef89280186, which is after `Boolean` type was removed in 4be1a0b23ad290. and after changing opcodes in 779bf687279bcca. 
We can create an issue and gradually enable test for specific opcodes like it was done for 2.0 .

**Comment by roman-khimov** [comment]
OK, I've thought that maybe these changes predate the big opcode change and can correlate to some earlier test set.

**Comment by roman-khimov** [comment]
Then it's worth setting 45928090908bea777962c6df5dec1dd1bbafd7a7 here as a target neo-vm test set (which is v3.0.0-preview2).

**Pull request merged**
