### PR TITLE
mpt: remove unrtraceable roots

### LINKED ISSUE #2095: MPT data cleanup for RemoveUntraceableBlocks
We have `KeepOnlyLatestState` to remove old MPT data, but it strips everything up to the latest state. We at the same time have `RemoveUntraceableBlocks` which makes node remove old blocks/transactions, but it doesn't do anything else. So if we're to have `KeepOnlyLatestState` set to `false` and `RemoveUntraceableBlocks` set to `true` the node will drop old blocks, but keep all MPTs at the same time which doesn't make a lot of sense. I think it'd be appropriate to drop old MPTs along with corresponding blocks in this configuration.

### PR DESCRIPTION
**Pull request by fyrchik**
Close #2095 .

It is ready to review but needs more opimization and testing.
Current implementation adds about 40% overhead on n3 dump restore.

### CODE REVIEW

**Comment by roman-khimov** [comment]
Just some raw data (`VerifyBlocks` is `false` everywhere, mainnet is up to 205990, testnet up to 278293):
```
MASTER (c9e62769a67e40f90a1cae67abd0ee0a288a44ae)

Level, mainnet

real    0m52,601s      real    0m56,376s      real    0m51,012s     
user    2m0,624s       user    2m5,673s       user    2m0,180s      
sys     0m10,817s      sys     0m10,200s      sys     0m10,512s     
1021M   chains/mainnet 856M    chains/mainnet 862M    chains/mainnet

BoltDB, mainnet

real    1m19,094s           real    1m19,235s	        real    1m19,271s	   
user    2m41,351s	    user    2m40,987s	   	user    2m40,694s	   
sys     0m25,426s	    sys     0m26,440s	   	sys     0m25,542s	   
1,8G    chains/mainnet.bolt 1,8G    chains/mainnet.bolt	1,9G    chains/mainnet.bolt

LevelDB, testnet

real    0m52,747s      real    1m0,108s       real    1m2,282s      
user    1m50,741s      user    1m59,676s      user    1m54,594s     
sys     0m9,903s       sys     0m10,334s      sys     0m11,474s     
1,1G    chains/testnet 1,1G    chains/testnet 1,1G    chains/testnet

BoltDB, testnet

real    1m7,032s            real    1m8,997s	        real    1m8,115s	   
user    2m17,352s	    user    2m16,786s	   	user    2m16,144s	   
sys     0m20,819s	    sys     0m22,862s	   	sys     0m22,279s	   
2,7G    chains/testnet.bolt 2,6G    chains/testnet.bolt	2,7G    chains/testnet.bolt


MASTER, KEEPONLYLATEST

LevelDB, mainnet

real    0m56,472s      real    0m56,364s      real    0m56,540s     
user    2m17,770s      user    2m17,623s      user    2m18,338s     
sys     0m8,059s       sys     0m8,261s       sys     0m8,319s      
191M    chains/mainnet 191M    chains/mainnet 191M    chains/mainnet

BoltDB, mainnet

real    0m48,314s           real    0m48,184s	        real    0m48,212s	   
user    2m4,629s	    user    2m3,064s	   	user    2m4,015s	   
sys     0m6,772s	    sys     0m6,699s	   	sys     0m7,070s	   
530M    chains/mainnet.bolt 548M    chains/mainnet.bolt	543M    chains/mainnet.bolt

LevelDB, testnet

real    0m58,701s      real    0m58,158s      real    0m58,367s     
user    2m26,263s      user    2m24,969s      user    2m25,023s     
sys     0m10,263s      sys     0m8,991s       sys     0m9,436s      
252M    chains/testnet 251M    chains/testnet 252M    chains/testnet

BoltDB, testnet

real    0m49,621s           real    0m49,167s	        real    0m49,583s	   
user    2m4,522s	    user    2m2,808s	   	user    2m3,814s	   
sys     0m7,929s	    sys     0m8,110s	   	sys     0m8,564s	   
708M    chains/testnet.bolt 706M    chains/testnet.bolt	713M    chains/testnet.bolt


PR2137, DEFAULT

LevelDB, mainnet

real    0m50,155s      real    0m56,584s      real    0m51,655s     
user    1m58,204s      user    2m6,770s       user    2m0,638s      
sys     0m10,187s      sys     0m10,471s      sys     0m10,228s     
855M    chains/mainnet 856M    chains/mainnet 855M    chains/mainnet

BoltDB, mainnet

real    1m17,509s           real    1m18,316s	        real    1m20,041s	   
user    2m38,221s	    user    2m38,305s	   	user    2m38,944s	   
sys     0m25,536s	    sys     0m25,728s	   	sys     0m27,987s	   
1,8G    chains/mainnet.bolt 1,9G    chains/mainnet.bolt	1,9G    chains/mainnet.bolt

LevelDB, testnet

real    1m0,448s       real    0m56,939s      real    0m54,406s     
user    1m53,676s      user    1m54,849s      user    1m52,981s     
sys     0m11,010s      sys     0m10,518s      sys     0m10,001s     
1,1G    chains/testnet 1,1G    chains/testnet 1,1G    chains/testnet

BoltDB, testnet

real    1m7,979s            real    1m8,112s	        real    1m8,066s	   
user    2m18,852s	    user    2m17,750s	   	user    2m17,508s	   
sys     0m21,430s	    sys     0m22,039s	   	sys     0m22,721s	   
2,7G    chains/testnet.bolt 2,7G    chains/testnet.bolt	2,6G    chains/testnet.bolt


PR2137, KEEPONLYLATEST

LevelDB, mainnet

real    0m56,919s      real    0m56,256s      real    0m56,820s     
user    2m18,815s      user    2m18,074s      user    2m18,794s     
sys     0m8,221s       sys     0m8,304s       sys     0m8,144s      
190M    chains/mainnet 191M    chains/mainnet 190M    chains/mainnet

BoltDB, mainnet

real    0m48,982s           real    0m49,103s	        real    0m48,865s	   
user    2m4,584s	    user    2m4,485s	   	user    2m5,517s	   
sys     0m6,975s	    sys     0m6,922s	   	sys     0m6,939s	   
497M    chains/mainnet.bolt 543M    chains/mainnet.bolt	546M    chains/mainnet.bolt

LevelDB, testnet

real    0m58,128s      real    0m58,180s      real    0m58,469s     
user    2m25,105s      user    2m25,579s      user    2m25,545s     
sys     0m9,427s       sys     0m9,294s       sys     0m9,236s      
250M    chains/testnet 251M    chains/testnet 251M    chains/testnet

BoltDB, testnet

real    0m49,994s           real    0m49,681s	        real    0m49,604s	   
user    2m3,804s	    user    2m4,659s	   	user    2m3,658s	   
sys     0m8,515s	    sys     0m8,202s	   	sys     0m8,812s	   
775M    chains/testnet.bolt 752M    chains/testnet.bolt	749M    chains/testnet.bolt


PR2159, DEFAULT

LevelDB, mainnet

real    0m51,254s      real    0m56,633s      real    0m52,292s     
user    1m58,990s      user    2m5,488s       user    2m0,585s      
sys     0m10,486s      sys     0m10,435s      sys     0m10,389s     
858M    chains/mainnet 856M    chains/mainnet 856M    chains/mainnet

BoltDB, mainnet

real    1m18,254s           real    1m18,021s	        real    1m18,668s	   
user    2m37,127s	    user    2m36,892s	   	user    2m36,108s	   
sys     0m27,147s	    sys     0m25,729s	   	sys     0m26,678s	   
1,9G    chains/mainnet.bolt 1,9G    chains/mainnet.bolt	1,9G    chains/mainnet.bolt

LevelDB, testnet

real    0m56,553s      real    0m57,648s      real    0m53,580s     
user    1m53,146s      user    1m55,158s      user    1m51,290s     
sys     0m11,237s      sys     0m9,941s       sys     0m9,887s      
1,1G    chains/testnet 1,1G    chains/testnet 1,1G    chains/testnet

BoltDB, testnet

real    1m7,292s            real    1m9,529s	        real    1m8,846s	   
user    2m19,104s	    user    2m20,408s	   	user    2m18,090s	   
sys     0m21,591s	    sys     0m23,234s	   	sys     0m21,232s	   
2,6G    chains/testnet.bolt 2,7G    chains/testnet.bolt	2,7G    chains/testnet.bolt


PR2159, KEEPONLYLATEST

LevelDB, mainnet

real    1m2,301s       real    1m3,568s       real    1m3,536s      
user    2m48,112s      user    2m48,011s      user    2m52,721s     
sys     0m13,822s      sys     0m13,398s      sys     0m14,077s     
639M    chains/mainnet 644M    chains/mainnet 670M    chains/mainnet

BoltDB, mainnet

real    1m22,354s           real    1m21,817s	        real    1m23,978s	   
user    3m7,237s	    user    3m2,407s	   	user    3m5,144s	   
sys     0m20,348s	    sys     0m20,512s	   	sys     0m23,211s	   
1,2G    chains/mainnet.bolt 1,3G    chains/mainnet.bolt	1,2G    chains/mainnet.bolt

LevelDB, testnet

real    1m5,041s       real    1m6,946s       real    1m5,066s      
user    2m41,476s      user    2m52,645s      user    2m41,010s     
sys     0m14,129s      sys     0m14,126s      sys     0m13,642s     
903M    chains/testnet 976M    chains/testnet 1,3G    chains/testnet

BoltDB, testnet

real    1m9,280s            real    1m11,914s	        real    1m11,293s	   
user    2m42,569s	    user    2m44,814s	   	user    2m42,979s	   
sys     0m15,574s	    sys     0m17,854s	   	sys     0m15,501s	   
2,0G    chains/testnet.bolt 1,6G    chains/testnet.bolt	2,0G    chains/testnet.bolt
```

But I've noticed that PR #2137 isn't tested properly, so I've set `RemoveUntraceableBlocks` to `true` and `MaxTraceableBlocks` to 10000 (with `KeepOnlyLatestState` set to `false`), then this has happened:
```
LevelDB, mainnet

real    2m42,568s      real    2m44,076s      real    2m42,596s
user    6m46,901s      user    6m50,155s      user    6m48,940s
sys     0m34,736s      sys     0m34,818s      sys     0m34,281s
260M    chains/mainnet 258M    chains/mainnet 246M    chains/mainnet

BoltDB, mainnet

real    1m29,876s           real    1m30,172s           real    1m29,845s
user    3m46,928s           user    3m46,211s           user    3m45,176s
sys     0m14,619s           sys     0m14,879s           sys     0m14,920s
753M    chains/mainnet.bolt 760M    chains/mainnet.bolt 747M    chains/mainnet.bolt

LevelDB, testnet

real    3m6,508s       real    2m58,228s      real    3m4,049s
user    7m51,111s      user    7m29,735s      user    7m41,653s
sys     0m40,283s      sys     0m39,434s      sys     0m39,784s
335M    chains/testnet 274M    chains/testnet 331M    chains/testnet

BoltDB, testnet

real    1m27,897s           real    1m27,415s           real    1m27,988s
user    3m52,714s           user    3m51,536s           user    3m52,725s
sys     0m14,546s           sys     0m14,655s           sys     0m14,941s
888M    chains/testnet.bolt 887M    chains/testnet.bolt 891M    chains/testnet.bolt
```
Notice that technically it keeps the same 10K states as GC-based PR.

**Comment by roman-khimov** [comment]
And the last, but actually the most interesting set of results. Here the node is configured to drop old blocks (with tracing depth of 10000) and at the same time only keep the latest state, but the code is modified to actually keep 3 states --- two previous synchronization points (with 10000 interval) and the current one. So it's the lightest configuration possible which is actually what we want for NeoFS chains (while still having enough data to bootstrap any other new node).
```
LevelDB, mainnet

real    1m39,181s      real    1m39,301s      real    1m39,245s
user    4m11,802s      user    4m10,561s      user    4m10,960s
sys     0m22,075s      sys     0m20,931s      sys     0m21,931s
893M    chains/mainnet 891M    chains/mainnet 880M    chains/mainnet

BoltDB, mainnet

real    1m17,969s           real    1m19,231s           real    1m17,796s
user    2m40,949s           user    2m41,010s           user    2m40,036s
sys     0m31,324s           sys     0m32,706s           sys     0m31,484s
1,9G    chains/mainnet.bolt 1,9G    chains/mainnet.bolt 1,9G    chains/mainnet.bolt

LevelDB, testnet

real    1m53,877s      real    1m54,934s      real    1m52,257s
user    4m34,303s      user    4m36,557s      user    4m27,691s
sys     0m25,678s      sys     0m26,297s      sys     0m25,435s
1,2G    chains/testnet 1,1G    chains/testnet 1,1G    chains/testnet

BoltDB, testnet

real    1m13,096s           real    1m15,921s           real    1m16,232s
user    2m33,576s           user    2m36,489s           user    2m35,309s
sys     0m28,540s           sys     0m29,553s           sys     0m31,852s
2,8G    chains/testnet.bolt 2,4G    chains/testnet.bolt 2,4G    chains/testnet.bolt
```

**Comment by roman-khimov** [comment]
We have several cases here:
 * full archive node in any config (stores everything)
 * public networks with `KeepOnlyLatestState` (only needs to store the latest state)
 * public networks with `RemoveUntraceableBlocks` (stores a `MaxTraceableBlocks` number of MPTs)
 * state-exchange networks with `RemoveUntraceableBlocks` (stores `MaxTraceableBlocks` and/or `2×StateSyncInterval` MPTs)
 * state-exchange networks with `KeepOnlyLatestState` (technically only needs three MPTs, the latest one and 2 sync points)

In my tests the last two are not much different from disk usage perspective, so we can probably always store a bigger number of MPTs. The first two work perfectly the way they are now. `RemoveUntraceableBlocks` cases are better covered by GC (#2159), I think, keeping a set of MPTs with #2137 can be very expensive. So my proposal would be:
 * keep "store everything" logic with no counting
 * keep reference counting logic for public networks as is
 * add GC for `RemoveUntraceableBlocks` case that will works instead of reference counting

@fyrchik, @AnnaShaleva? @fyrchik, you can also test "three points" case additionally, maybe it'd be somewhat different on your machine, but for me it's easier to store 10000 MPTs with #2159 than exactly 3 with #2137.

**Comment by fyrchik** [comment]
@roman-khimov I will rebase and test this. I think we can have GC implementation along with this one to make it easier to test (though I am not sure it is faster).

**Comment by fyrchik** [comment]
I have benched the following configurations (testnet dump with ~350k blocks; everything was benched 3 times, the results were the same):
1. `RemoveUntraceableBlocks: true` with `MaxTraceableBlocks: 10000`:
```
# master
LevelDB
________________________________________________________
Executed in  113,63 secs    fish           external
   usr time  193,48 secs    0,00 millis  193,48 secs
   sys time   19,69 secs    1,77 millis   19,68 secs

Bolt
________________________________________________________
Executed in  127,90 secs    fish           external
   usr time  268,54 secs    0,00 millis  268,54 secs
   sys time   20,48 secs    1,75 millis   20,48 secs

# reference counting
LevelDB
________________________________________________________
Executed in  101,88 secs    fish           external
   usr time  226,46 secs    0,00 millis  226,46 secs
   sys time   20,55 secs    1,31 millis   20,55 secs

Bolt
________________________________________________________
Executed in   72,38 secs    fish           external
   usr time  157,19 secs  819,00 micros  157,19 secs
   sys time   10,74 secs  455,00 micros   10,74 secs

# GC
LevelDB
________________________________________________________
Executed in  106,85 secs    fish           external
   usr time  202,80 secs  809,00 micros  202,80 secs
   sys time   20,69 secs  470,00 micros   20,69 secs

Bolt
________________________________________________________
Executed in  124,46 secs    fish           external
   usr time  271,11 secs    1,25 millis  271,11 secs
   sys time   24,49 secs    0,00 millis   24,49 secs

# GC, but wait for the last gc cycle to finish
LevelDB
_____
Executed in  114,00 secs    fish           external
   usr time  214,89 secs  967,00 micros  214,89 secs
   sys time   23,79 secs  510,00 micros   23,79 secs

Bolt (last GC cycle took 7 minutes and varied greatly between iterations)
________________________________________________________
Executed in  447,90 secs    fish           external
   usr time  506,86 secs  974,00 micros  506,86 secs
   sys time   71,97 secs  508,00 micros   71,97 secs

```

2. Reference counting with GenerationSpan set to 10k (i.e. we store only some of the last sync points if StateSyncInterval=10k) compared with master + KeepOnlyLatestState
```
# master
LevelDB
________________________________________________________
Executed in   96,59 secs    fish           external
   usr time  204,93 secs  731,00 micros  204,93 secs
   sys time   18,53 secs  476,00 micros   18,53 secs

Bolt
________________________________________________________
Executed in   68,00 secs    fish           external
   usr time  141,78 secs    0,00 millis  141,78 secs
   sys time    9,86 secs    1,68 millis    9,86 secs

# Multiple sync points
LevelDB
________________________________________________________
Executed in  101,33 secs    fish           external
   usr time  219,40 secs    1,10 millis  219,40 secs
   sys time   21,29 secs    0,55 millis   21,29 secs

Bolt
________________________________________________________
Executed in   71,01 secs    fish           external
   usr time  152,08 secs  835,00 micros  152,08 secs
   sys time   10,60 secs  465,00 micros   10,60 secs
```

**Comment by fyrchik** [comment]
There is a problem with GC which we currently don't address (and IMO this is the main reason for it to be slow): generation update is done for all items, but many of them (hypothetically) are long lived. So we traverse these nodes on each GC cycle. Also this traversal takes a lot more time than actual deletion with `Seek`.
I am thinking about some clever pruning (if an item is old and reachable, all of its children are also reachable). The need to save generation before the GC cycle (because it can take a lot and we must consider all cases) is the biggest issue so far.

**Comment by roman-khimov** [comment]
Old and slow.

**Pull request closed without merging**
