### PR TITLE
vm, compiler: support `ASSERTMSG` and `ABORTMSG`

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Port https://github.com/neo-project/neo-vm/pull/491, ready for review.

TODO:

- [x] Wait for the neo-project core update to set the opcodes price.
- [x] Update interop deps after PR is settle.

### CODE REVIEW

**Review by roman-khimov — COMMENTED** [review]
I don't see an update to `pkg/vm/testdata/neo-vm`, but it should be made since neo-project/neo-vm#491 has introduced some new tests.

**Comment by AnnaShaleva** [comment]
> I don't see an update to `pkg/vm/testdata/neo-vm`

Shouldn't the update be done locally? Each time I'd like to update submodules I perform
```
git submodule update --init
```
or just
```
git submodule update
```
and new commits are being fetched.

Our testing job perform the same thing:
```
      - name: Sync VM submodule
        run: |
          git submodule sync
          git submodule update --init
```
Where should I add an update?

And I've fixed the JSON testdata path, it was wrong since https://github.com/neo-project/neo-vm/commit/5a11f4b4cad43a78410f070216a000779f838355.

**Comment by roman-khimov** [comment]
You need to go down into `pkg/vm/testdata/neo-vm`, do a regular `git remote update && git rebase origin/master` and then you'll see a change in the index. Commit it and only then others will see this update on `git submodule update`.

**Comment by AnnaShaleva** [comment]
> git rebase origin/master

I performed it in the clean repo, and I don't have anything to commit after all these steps:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ git checkout abort-msg 
Switched to branch 'abort-msg'
Your branch is up to date with 'origin/abort-msg'.
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ cd pkg/vm/testdata/neo-vm/
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go/pkg/vm/testdata/neo-vm$ git remote update
Fetching origin
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go/pkg/vm/testdata/neo-vm$ git rebase origin/master
HEAD is up to date.
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go/pkg/vm/testdata/neo-vm$ git status
HEAD detached at 7e59968
nothing to commit, working tree clean
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go/pkg/vm/testdata/neo-vm$ cdw
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ git status
On branch abort-msg
Your branch is up to date with 'origin/abort-msg'.

nothing to commit, working tree clean
```

**Comment by AnnaShaleva** [comment]
And our testing jobs fetches the proper commit without any updates from my side:
image

**Comment by AnnaShaleva** [comment]
And moreover, with the [old NeoVM JSON test path](https://github.com/nspcc-dev/neo-go/pull/3066/commits/d05391e286ab70ba9167228125205d53459cb014) our testing job is failing with the following error:
```
2023-08-10T09:45:07.9164810Z === RUN   TestUT
2023-08-10T09:45:07.9165000Z     json_test.go:110: 
2023-08-10T09:45:07.9165641Z         	Error Trace:	/home/runner/work/neo-go/neo-go/pkg/vm/json_test.go:110
2023-08-10T09:45:07.9165856Z         	Error:      	Not equal: 
2023-08-10T09:45:07.9166152Z         	            	expected: true
2023-08-10T09:45:07.9166442Z         	            	actual  : false
2023-08-10T09:45:07.9166619Z         	Test:       	TestUT
2023-08-10T09:45:07.9167571Z         	Messages:   	neo-vm tests should be available (check submodules)
2023-08-10T09:45:07.9167715Z --- FAIL: TestUT (0.00s)
```
which means that the job can't find tests by the specified path. It is expected, because the path was updated in the NeoVM. See the job report: https://github.com/nspcc-dev/neo-go/actions/runs/5819454595/job/15777873680?pr=3066.

**Comment by roman-khimov** [comment]
We have and we should always have a particular commit used for `pkg/vm/testdata/neo-vm`. Then we update it as needed. Like in e66e82278c3cb600be5a03465e49fb5fd379010c or 3e6ce3c221cc413afb749f6fec2d791383493570.

**Comment by roman-khimov** [comment]
The problem is 0d17273476c5363a0b8c7ff76854ad6571cdccc2 in fact, it accidentally touched the submodule and no one noticed.

**Comment by AnnaShaleva** [comment]
> The problem is https://github.com/nspcc-dev/neo-go/commit/0d17273476c5363a0b8c7ff76854ad6571cdccc2 in fact

😱

**Comment by AnnaShaleva** [comment]
OK, this https://github.com/nspcc-dev/neo-go/commit/0d17273476c5363a0b8c7ff76854ad6571cdccc2 has updated the submodule up to the latest 7e59968 NeoVM commit, let this record be here, and thus we don't have to update the submodule in this PR.

**Review by roman-khimov — APPROVED** [review]

**Pull request merged**
