### PR TITLE
rpcsrv: fix TestFilteredNotaryRequestSubscriptions

### LINKED ISSUE #3378: WS-based RPC server tests fail on Windows
Go 1.22, Windows, e10c584d422d3997b68128231f05a0c68e67aa49. The failure error `read tcp 127.0.0.1:59625->127.0.0.1:59624: i/o timeout` looks exactly like in the previously failing `TestRPC` (#3314). To solve it we should try the same approach as the one used in #3368.

```
2024-03-27T13:28:35.7306245Z === NAME  TestFilteredNotaryRequestSubscriptions
2024-03-27T13:28:35.7306897Z     logger.go:146: 2024-03-27T13:23:17.951Z	DEBUG	processing rpc request	{"method": "subscribe", "params": "[notary_request_event ]"}
2024-03-27T13:28:35.7307032Z     subscription_test.go:36: 
2024-03-27T13:28:35.7307520Z         	Error Trace:	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:36
2024-03-27T13:28:35.7308127Z         	            				C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/asm_amd64.s:1695
2024-03-27T13:28:35.7308336Z         	Error:      	Received unexpected error:
2024-03-27T13:28:35.7308816Z         	            	read tcp 127.0.0.1:59625->127.0.0.1:59624: i/o timeout
2024-03-27T13:28:35.7309122Z         	Test:       	TestFilteredNotaryRequestSubscriptions
2024-03-27T13:28:35.7309869Z     logger.go:146: 2024-03-27T13:23:18.541Z	INFO	persisted to disk	{"blocks": 8, "keys": 771, "headerHeight": 23, "blockHeight": 23, "took": "0s"}
2024-03-27T13:28:35.7309979Z panic: test timed out after 15m0s
2024-03-27T13:28:35.7310066Z running tests:
2024-03-27T13:28:35.7310240Z 	TestFilteredNotaryRequestSubscriptions (3m7s)
2024-03-27T13:28:35.7310485Z 	TestFilteredNotaryRequestSubscriptions/matching_signer (3m6s)
2024-03-27T13:28:35.7310492Z 
2024-03-27T13:28:35.7310583Z goroutine 14131 [running]:
2024-03-27T13:28:35.7310683Z testing.(*M).startAlarm.func1()
2024-03-27T13:28:35.7310968Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:2366 +0x265
2024-03-27T13:28:35.7311057Z created by time.goFunc
2024-03-27T13:28:35.7311317Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/time/sleep.go:177 +0x45
2024-03-27T13:28:35.7311323Z 
2024-03-27T13:28:35.7311438Z goroutine 1 [chan receive, 3 minutes]:
2024-03-27T13:28:35.7311631Z testing.(*T).Run(0xc0002d6680, {0x141581c75, 0x26}, 0x141687388)
2024-03-27T13:28:35.7311943Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1750 +0x851
2024-03-27T13:28:35.7312087Z testing.runTests.func1(0xc0002d6680)
2024-03-27T13:28:35.7312370Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:2161 +0x86
2024-03-27T13:28:35.7312493Z testing.tRunner(0xc0002d6680, 0xc000217b10)
2024-03-27T13:28:35.7312773Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1689 +0x21f
2024-03-27T13:28:35.7313119Z testing.runTests(0xc0002f0be8, {0x1412d57e0, 0x31, 0x31}, {0xc000217bb8?, 0xc000217c00?, 0x1421220e0?})
2024-03-27T13:28:35.7313391Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:2159 +0x8bf
2024-03-27T13:28:35.7313486Z testing.(*M).Run(0xc0002834a0)
2024-03-27T13:28:35.7313747Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:2027 +0xf18
2024-03-27T13:28:35.7313829Z main.main()
2024-03-27T13:28:35.7313935Z 	_testmain.go:145 +0x2be
2024-03-27T13:28:35.7313942Z 
2024-03-27T13:28:35.7314070Z goroutine 14148 [chan receive, 3 minutes]:
2024-03-27T13:28:35.7314394Z github.com/nspcc-dev/neo-go/pkg/network/bqueue.(*Queue).Run(0xc00051d500)
2024-03-27T13:28:35.7314638Z 	D:/a/neo-go/neo-go/pkg/network/bqueue/queue.go:60 +0x9b
2024-03-27T13:28:35.7315006Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7315222Z 	D:/a/neo-go/neo-go/pkg/network/server.go:296 +0x605
2024-03-27T13:28:35.7315233Z 
2024-03-27T13:28:35.7315324Z goroutine 4997 [runnable]:
2024-03-27T13:28:35.7315430Z sync/atomic.(*Value).Load(0xc0006e52d8)
2024-03-27T13:28:35.7315706Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/sync/atomic/value.go:28 +0xf9
2024-03-27T13:28:35.7315812Z context.(*cancelCtx).Done(0xc0006e52c0)
2024-03-27T13:28:35.7316081Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/context/context.go:439 +0x50
2024-03-27T13:28:35.7316419Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*Internal).eventLoop(0xc000f6cc40)
2024-03-27T13:28:35.7316635Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:55 +0x73
2024-03-27T13:28:35.7316993Z created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewInternal in goroutine 4959
2024-03-27T13:28:35.7317204Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:45 +0x3cd
2024-03-27T13:28:35.7317209Z 
2024-03-27T13:28:35.7317302Z goroutine 14154 [select]:
2024-03-27T13:28:35.7317604Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).runProto(0xc0001ebc08)
2024-03-27T13:28:35.7317817Z 	D:/a/neo-go/neo-go/pkg/network/server.go:553 +0x229
2024-03-27T13:28:35.7318169Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).run in goroutine 14150
2024-03-27T13:28:35.7318374Z 	D:/a/neo-go/neo-go/pkg/network/server.go:453 +0x295
2024-03-27T13:28:35.7318379Z 
2024-03-27T13:28:35.7318480Z goroutine 14127 [select, 3 minutes]:
2024-03-27T13:28:35.7318804Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).txHandlerLoop(0xc0001ebc08)
2024-03-27T13:28:35.7319062Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1155 +0x23c
2024-03-27T13:28:35.7319504Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7319717Z 	D:/a/neo-go/neo-go/pkg/network/server.go:291 +0x31c
2024-03-27T13:28:35.7319723Z 
2024-03-27T13:28:35.7319822Z goroutine 14128 [select, 3 minutes]:
2024-03-27T13:28:35.7320151Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).txHandlerLoop(0xc0001ebc08)
2024-03-27T13:28:35.7320364Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1155 +0x23c
2024-03-27T13:28:35.7320718Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7320926Z 	D:/a/neo-go/neo-go/pkg/network/server.go:291 +0x31c
2024-03-27T13:28:35.7320931Z 
2024-03-27T13:28:35.7321018Z goroutine 14118 [select]:
2024-03-27T13:28:35.7321307Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).Run(0xc000315208)
2024-03-27T13:28:35.7321529Z 	D:/a/neo-go/neo-go/pkg/core/blockchain.go:1074 +0x2dc
2024-03-27T13:28:35.7322102Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.getUnitTestChainWithCustomConfig in goroutine 14116
2024-03-27T13:28:35.7322453Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server_helper_test.go:85 +0x737
2024-03-27T13:28:35.7322459Z 
2024-03-27T13:28:35.7322552Z goroutine 5019 [runnable]:
2024-03-27T13:28:35.7323027Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).notifySubscribers(0xc000f6ce00, {0x0?, {0x0?, 0x0?}})
2024-03-27T13:28:35.7323260Z 	D:/a/neo-go/neo-go/pkg/rpcclient/wsclient.go:683 +0x629
2024-03-27T13:28:35.7323594Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*Internal).eventLoop(0xc000f6ce00)
2024-03-27T13:28:35.7323800Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:64 +0x47
2024-03-27T13:28:35.7324162Z created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewInternal in goroutine 5013
2024-03-27T13:28:35.7324711Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:45 +0x3cd
2024-03-27T13:28:35.7324719Z 
2024-03-27T13:28:35.7324841Z goroutine 14120 [IO wait, 3 minutes]:
2024-03-27T13:28:35.7324996Z internal/poll.runtime_pollWait(0x48719fd8, 0x72)
2024-03-27T13:28:35.7325270Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/netpoll.go:345 +0x85
2024-03-27T13:28:35.7325444Z internal/poll.(*pollDesc).wait(0xc001b030c0, 0x72, 0x0)
2024-03-27T13:28:35.7325780Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-27T13:28:35.7325923Z internal/poll.execIO(0xc001b02f20, 0xc000059930)
2024-03-27T13:28:35.7326236Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:175 +0x271
2024-03-27T13:28:35.7326539Z internal/poll.(*FD).acceptOne(0xc001b02f08, 0x494, {0xc000925680, 0x2, 0x2}, 0xc001b02f20)
2024-03-27T13:28:35.7326850Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:944 +0xf8
2024-03-27T13:28:35.7327013Z internal/poll.(*FD).Accept(0xc001b02f08, 0xc001007ba8)
2024-03-27T13:28:35.7327326Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:978 +0x3cb
2024-03-27T13:28:35.7327429Z net.(*netFD).accept(0xc001b02f08)
2024-03-27T13:28:35.7327698Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/fd_windows.go:178 +0x85
2024-03-27T13:28:35.7327810Z net.(*TCPListener).accept(0xc003bc4400)
2024-03-27T13:28:35.7328089Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock_posix.go:159 +0x3e
2024-03-27T13:28:35.7328198Z net.(*TCPListener).Accept(0xc003bc4400)
2024-03-27T13:28:35.7328445Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock.go:327 +0x65
2024-03-27T13:28:35.7328654Z net/http.(*Server).Serve(0xc000c5ca50, {0x141869d20, 0xc003bc4400})
2024-03-27T13:28:35.7328919Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/http/server.go:3255 +0x672
2024-03-27T13:28:35.7329301Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start.func1(0xc000c5ca50)
2024-03-27T13:28:35.7329552Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server.go:403 +0x79
2024-03-27T13:28:35.7330035Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7330326Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server.go:402 +0x1c5
2024-03-27T13:28:35.7330334Z 
2024-03-27T13:28:35.7330443Z goroutine 14122 [select, 3 minutes]:
2024-03-27T13:28:35.7330820Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).notificationDispatcher(0xc000315208)
2024-03-27T13:28:35.7331043Z 	D:/a/neo-go/neo-go/pkg/core/blockchain.go:1336 +0x4b6
2024-03-27T13:28:35.7331411Z created by github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).Run in goroutine 14118
2024-03-27T13:28:35.7331626Z 	D:/a/neo-go/neo-go/pkg/core/blockchain.go:1071 +0x18b
2024-03-27T13:28:35.7331632Z 
2024-03-27T13:28:35.7331737Z goroutine 14126 [select, 3 minutes]:
2024-03-27T13:28:35.7332069Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).txHandlerLoop(0xc0001ebc08)
2024-03-27T13:28:35.7332286Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1155 +0x23c
2024-03-27T13:28:35.7332648Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7332860Z 	D:/a/neo-go/neo-go/pkg/network/server.go:291 +0x31c
2024-03-27T13:28:35.7332870Z 
2024-03-27T13:28:35.7333007Z goroutine 14146 [select, 3 minutes]:
2024-03-27T13:28:35.7333377Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).relayBlocksLoop(0xc0001ebc08)
2024-03-27T13:28:35.7333595Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1589 +0x225
2024-03-27T13:28:35.7333956Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7334170Z 	D:/a/neo-go/neo-go/pkg/network/server.go:294 +0x4ab
2024-03-27T13:28:35.7334175Z 
2024-03-27T13:28:35.7334287Z goroutine 14149 [IO wait, 3 minutes]:
2024-03-27T13:28:35.7334431Z internal/poll.runtime_pollWait(0x48798080, 0x72)
2024-03-27T13:28:35.7334700Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/netpoll.go:345 +0x85
2024-03-27T13:28:35.7334867Z internal/poll.(*pollDesc).wait(0xc001b03ac0, 0x72, 0x0)
2024-03-27T13:28:35.7335205Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-27T13:28:35.7335344Z internal/poll.execIO(0xc001b03920, 0xc0003e59e0)
2024-03-27T13:28:35.7335660Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:175 +0x271
2024-03-27T13:28:35.7335959Z internal/poll.(*FD).acceptOne(0xc001b03908, 0x2a0, {0xc000925770, 0x2, 0x2}, 0xc001b03920)
2024-03-27T13:28:35.7336274Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:944 +0xf8
2024-03-27T13:28:35.7336434Z internal/poll.(*FD).Accept(0xc001b03908, 0xc0005e5c58)
2024-03-27T13:28:35.7336745Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:978 +0x3cb
2024-03-27T13:28:35.7336848Z net.(*netFD).accept(0xc001b03908)
2024-03-27T13:28:35.7337105Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/fd_windows.go:178 +0x85
2024-03-27T13:28:35.7337217Z net.(*TCPListener).accept(0xc003bc4680)
2024-03-27T13:28:35.7337491Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock_posix.go:159 +0x3e
2024-03-27T13:28:35.7337604Z net.(*TCPListener).Accept(0xc003bc4680)
2024-03-27T13:28:35.7337848Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock.go:327 +0x65
2024-03-27T13:28:35.7338181Z github.com/nspcc-dev/neo-go/pkg/network.(*TCPTransport).Accept(0xc0014844d0)
2024-03-27T13:28:35.7338430Z 	D:/a/neo-go/neo-go/pkg/network/tcp_transport.go:78 +0x448
2024-03-27T13:28:35.7338793Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7339005Z 	D:/a/neo-go/neo-go/pkg/network/server.go:298 +0x63d
2024-03-27T13:28:35.7339010Z 
2024-03-27T13:28:35.7339112Z goroutine 14125 [select, 3 minutes]:
2024-03-27T13:28:35.7339444Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).txHandlerLoop(0xc0001ebc08)
2024-03-27T13:28:35.7339660Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1155 +0x23c
2024-03-27T13:28:35.7340023Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7340268Z 	D:/a/neo-go/neo-go/pkg/network/server.go:291 +0x31c
2024-03-27T13:28:35.7340304Z 
2024-03-27T13:28:35.7340405Z goroutine 14150 [select, 3 minutes]:
2024-03-27T13:28:35.7340690Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).run(0xc0001ebc08)
2024-03-27T13:28:35.7340894Z 	D:/a/neo-go/neo-go/pkg/network/server.go:484 +0x919
2024-03-27T13:28:35.7341249Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7341450Z 	D:/a/neo-go/neo-go/pkg/network/server.go:303 +0x874
2024-03-27T13:28:35.7341455Z 
2024-03-27T13:28:35.7341580Z goroutine 14147 [chan receive, 3 minutes]:
2024-03-27T13:28:35.7341885Z github.com/nspcc-dev/neo-go/pkg/network/bqueue.(*Queue).Run(0xc00051d480)
2024-03-27T13:28:35.7342114Z 	D:/a/neo-go/neo-go/pkg/network/bqueue/queue.go:60 +0x9b
2024-03-27T13:28:35.7342466Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7342666Z 	D:/a/neo-go/neo-go/pkg/network/server.go:295 +0x557
2024-03-27T13:28:35.7342673Z 
2024-03-27T13:28:35.7342770Z goroutine 4714 [runnable]:
2024-03-27T13:28:35.7342877Z sync/atomic.(*Value).Load(0xc0007f4dd8)
2024-03-27T13:28:35.7343191Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/sync/atomic/value.go:36 +0x93
2024-03-27T13:28:35.7343330Z context.(*cancelCtx).Done(0xc0007f4dc0)
2024-03-27T13:28:35.7343598Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/context/context.go:439 +0x50
2024-03-27T13:28:35.7343932Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*Internal).eventLoop(0xc0007b3880)
2024-03-27T13:28:35.7344137Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:55 +0x73
2024-03-27T13:28:35.7344496Z created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewInternal in goroutine 4708
2024-03-27T13:28:35.7344699Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:45 +0x3cd
2024-03-27T13:28:35.7344704Z 
2024-03-27T13:28:35.7344828Z goroutine 14116 [chan receive, 3 minutes]:
2024-03-27T13:28:35.7345014Z testing.(*T).Run(0xc0002dba00, {0x141561446, 0xf}, 0xc0036ba900)
2024-03-27T13:28:35.7345290Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1750 +0x851
2024-03-27T13:28:35.7345781Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.TestFilteredNotaryRequestSubscriptions(0xc0002dba00)
2024-03-27T13:28:35.7346098Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:403 +0x792
2024-03-27T13:28:35.7346219Z testing.tRunner(0xc0002dba00, 0x141687388)
2024-03-27T13:28:35.7346490Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1689 +0x21f
2024-03-27T13:28:35.7346612Z created by testing.(*T).Run in goroutine 1
2024-03-27T13:28:35.7346871Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1742 +0x826
2024-03-27T13:28:35.7346876Z 
2024-03-27T13:28:35.7346982Z goroutine 14119 [select, 3 minutes]:
2024-03-27T13:28:35.7347361Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleSubEvents(0xc001b02a08)
2024-03-27T13:28:35.7347617Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server.go:2920 +0x86d
2024-03-27T13:28:35.7348026Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7348269Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server.go:390 +0xf4
2024-03-27T13:28:35.7348275Z 
2024-03-27T13:28:35.7348379Z goroutine 14124 [select, 3 minutes]:
2024-03-27T13:28:35.7348729Z github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).notificationDispatcher(...)
2024-03-27T13:28:35.7348968Z 	D:/a/neo-go/neo-go/pkg/core/mempool/subscriptions.go:55
2024-03-27T13:28:35.7349419Z created by github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).RunSubscriptions in goroutine 14116
2024-03-27T13:28:35.7349688Z 	D:/a/neo-go/neo-go/pkg/core/mempool/subscriptions.go:13 +0xe5
2024-03-27T13:28:35.7349694Z 
2024-03-27T13:28:35.7349793Z goroutine 14129 [select, 3 minutes]:
2024-03-27T13:28:35.7350134Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).broadcastTxLoop(0xc0001ebc08)
2024-03-27T13:28:35.7350351Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1689 +0x33b
2024-03-27T13:28:35.7350745Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 14116
2024-03-27T13:28:35.7350993Z 	D:/a/neo-go/neo-go/pkg/network/server.go:293 +0x42b
2024-03-27T13:28:35.7350999Z 
2024-03-27T13:28:35.7351104Z goroutine 14121 [IO wait, 3 minutes]:
2024-03-27T13:28:35.7351249Z internal/poll.runtime_pollWait(0x485ecf80, 0x72)
2024-03-27T13:28:35.7351517Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/netpoll.go:345 +0x85
2024-03-27T13:28:35.7351680Z internal/poll.(*pollDesc).wait(0xc001b03340, 0x72, 0x0)
2024-03-27T13:28:35.7352018Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-27T13:28:35.7352155Z internal/poll.execIO(0xc001b031a0, 0xc0003e99f8)
2024-03-27T13:28:35.7352467Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:175 +0x271
2024-03-27T13:28:35.7352765Z internal/poll.(*FD).acceptOne(0xc001b03188, 0x49c, {0xc00084a0f0, 0x2, 0x2}, 0xc001b031a0)
2024-03-27T13:28:35.7353078Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:944 +0xf8
2024-03-27T13:28:35.7353238Z internal/poll.(*FD).Accept(0xc001b03188, 0xc00077dc70)
2024-03-27T13:28:35.7353585Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:978 +0x3cb
2024-03-27T13:28:35.7353723Z net.(*netFD).accept(0xc001b03188)
2024-03-27T13:28:35.7353981Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/fd_windows.go:178 +0x85
2024-03-27T13:28:35.7354094Z net.(*TCPListener).accept(0xc003bc4420)
2024-03-27T13:28:35.7354366Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock_posix.go:159 +0x3e
2024-03-27T13:28:35.7354478Z net.(*TCPListener).Accept(0xc003bc4420)
2024-03-27T13:28:35.7354722Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock.go:327 +0x65
2024-03-27T13:28:35.7354928Z net/http.(*Server).Serve(0xc000c5cb40, {0x141869d20, 0xc003bc4420})
2024-03-27T13:28:35.7355195Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/http/server.go:3255 +0x672
2024-03-27T13:28:35.7355321Z net/http/httptest.(*Server).goServe.func1()
2024-03-27T13:28:35.7355635Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/http/httptest/server.go:310 +0xbc
2024-03-27T13:28:35.7355859Z created by net/http/httptest.(*Server).goServe in goroutine 14116
2024-03-27T13:28:35.7356172Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/http/httptest/server.go:308 +0xa6
2024-03-27T13:28:35.7356177Z 
2024-03-27T13:28:35.7356295Z goroutine 14265 [chan receive, 3 minutes]:
2024-03-27T13:28:35.7356881Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.callWSGetRaw(0xc0001916c0, 0xc0021242c0, {0xc0001d2990, 0x8a}, 0xc000a8ab40)
2024-03-27T13:28:35.7357194Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:47 +0x176
2024-03-27T13:28:35.7357760Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.callSubscribe(0xc0001916c0, 0xc0021242c0, 0xc000a8ab40, {0xc0008e0190, 0x4f})
2024-03-27T13:28:35.7358071Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:78 +0x115
2024-03-27T13:28:35.7358595Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.TestFilteredNotaryRequestSubscriptions.func5(0xc0001916c0)
2024-03-27T13:28:35.7358908Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:404 +0xbf
2024-03-27T13:28:35.7359029Z testing.tRunner(0xc0001916c0, 0xc0036ba900)
2024-03-27T13:28:35.7359304Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1689 +0x21f
2024-03-27T13:28:35.7359443Z created by testing.(*T).Run in goroutine 14116
2024-03-27T13:28:35.7359715Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1742 +0x826
2024-03-27T13:28:35.7359725Z 
2024-03-27T13:28:35.7359819Z goroutine 5424 [runnable]:
2024-03-27T13:28:35.7360303Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).notifySubscribers(0xc00053a8c0, {0xd4?, {0x0?, 0x0?}})
2024-03-27T13:28:35.7360543Z 	D:/a/neo-go/neo-go/pkg/rpcclient/wsclient.go:694 +0x172
2024-03-27T13:28:35.7366576Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*Internal).eventLoop(0xc00053a8c0)
2024-03-27T13:28:35.7366942Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:64 +0x47
2024-03-27T13:28:35.7367377Z created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewInternal in goroutine 5387
2024-03-27T13:28:35.7367609Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:45 +0x3cd
2024-03-27T13:28:35.7367871Z FAIL	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv	900.168s
```

### PR DESCRIPTION
**Pull request by AliceInHunterland**
Close #3378

### CODE REVIEW

**Comment by AliceInHunterland** [comment]
o no. 
```
2024-03-29T06:47:52.2085630Z === NAME  TestRPC/http/single_request/invokescript/positive,_good_witness
2024-03-29T06:47:52.2085840Z     server_test.go:3501: 
2024-03-29T06:47:52.2087050Z         	Error Trace:	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server_test.go:3501
2024-03-29T06:47:52.2088340Z         	            				/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server_test.go:2519
2024-03-29T06:47:52.2088700Z         	Error:      	Received unexpected error:
2024-03-29T06:47:52.2089900Z         	            	Post "http://127.0.0.1:50203": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-03-29T06:47:52.2090720Z         	Test:       	TestRPC/http/single_request/invokescript/positive,_good_witness
2024-03-29T06:47:52.2091310Z         	Messages:   	could not make a POST request
```
@AnnaShaleva can I add a commit with changes for TestRPC here, in this pr? The solution I think is the same - increase the timeout to 5 sec.

**Review by AnnaShaleva — COMMENTED** [review]
I don't see how this PR can help with failing `TestFilteredNotaryRequestSubscriptions`, although the fix itself is valid. The fix is ported to https://github.com/nspcc-dev/neo-go/pull/3387.

**Comment by AnnaShaleva** [comment]
> The solution I think is the same - increase the timeout to 5 sec.

Let me check. If needed, then the fix may be added in a separate PR.

**Comment by AnnaShaleva** [comment]
Replaced by #3387.

**Pull request closed without merging**
