### PR TITLE
core: update committee every [committee length] blocks

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Was changed in https://github.com/neo-project/neo/pull/1848. Affects
storage dumps.

### CODE REVIEW

**Comment by AnnaShaleva** [comment]
Not sure, what should I do with the test. Voting in our SingleTestChain occurs every single block, because we have the only validator in committee.

**Comment by fyrchik** [comment]
@AnnaShaleva I think, we may extend the committee in config for a single node. Interesting to see if it breaks any other tests.

**Comment by roman-khimov** [comment]
> Voting in our SingleTestChain occurs every single block, because we have the only validator in committee.

And it's a perfect edge case that must be handled correctly. Extending the committee is OK for some particular test (like the one that want to vote two blocks before committee refresh, but this edge case must be tested too.

@fyrchik --- where is a PR for neo-project/neo#2062? I'm OK with merging this if you have an appropriate update, but otherwise we need to fix the test here.

**Comment by roman-khimov** [comment]
@fyrchik --- is it possible to fix the test here without #1552?

**Comment by fyrchik** [comment]
@roman-khimov as I wrote, yes, but we need to extend the committee in unittest cfg. Or just make 2-nd test similar to the first and postpone config update.

**Review by roman-khimov — APPROVED** [review]

**Pull request merged**
