### PR TITLE
core: managment contract updates

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Changes ported from https://github.com/neo-project/neo/pull/2140, https://github.com/neo-project/neo/pull/2153 and https://github.com/neo-project/neo/pull/2150.

TBD:
- [x] Tests for MinimumDeploymentFee getter/setter (depends on #1615, there's a useful tests refactoring)

- [x] Tests for notifications

### CODE REVIEW

**Comment by fyrchik** [comment]
It shouldn't be hard to also check if notification was emitted in current tests.

**Comment by roman-khimov** [comment]
> Cache for MinimumDeploymentFee

Not really critical for now, deployments are rare.

**Comment by AnnaShaleva** [comment]
> > Cache for MinimumDeploymentFee
> 
> Not really critical for now, deployments are rare.

OK, then all things are done. I believe that we can update MaxGASInvoke RPC configuration for mainnet, testnet and privnet later to be consistent with C# node because we don't know the proper values at the current moment.

**Comment by roman-khimov** [comment]
@fyrchik, please review.

**Review by fyrchik — APPROVED** [review]

**Pull request merged**
