### PR TITLE
Drop CircleCI support

### PR DESCRIPTION
**Pull request by roman-khimov**
It stopped running our tests/builds, but we don't care, Github works well.

### CODE REVIEW

**Review by AnnaShaleva — APPROVED** [review]

**Comment by AnnaShaleva** [comment]
Not sure why, but we still have the `CircleCI Pipeline — No configuration was found in your project. Please refer to https://circleci.com/docs/2` failing check. Do we need to remove CircleCI from elsewhere?

**Comment by roman-khimov** [comment]
Where do you see this?

**Comment by AnnaShaleva** [comment]
image

**Comment by AnnaShaleva** [comment]
GA workers fetching action's config from the PR branch (not from master), and I thought that CircleCI jobs do the same thing, but not sure whether it's true. We may check it in some new PR.

**Comment by roman-khimov** [comment]
I've checked our integration keys/webhooks yesterday and thought that we have nothing else left. OK, let's wait for another PR and see how it goes.

**Pull request merged**
