### PR TITLE
*: several Notary subsystem adjustments, part 2

### PR DESCRIPTION
**Pull request by AnnaShaleva**
Waiting for the final decision on constants/limits.

Depends on #2378.

TODO:

- [x] Update interop dependencies right before the merge.

### CODE REVIEW

**Comment by roman-khimov** [comment]
Can we rebase it to see the current list of remaining changes?

**Comment by AnnaShaleva** [comment]
> Can we rebase it to see the current list of remaining changes?

Yes, but I found one more bug in snapshot isolation and trying to test it for the C# node. After that I'll rebase it.

**Comment by AnnaShaleva** [comment]
Speaking of [valuable constants](https://github.com/neo-project/neo/pull/2425#issuecomment-1010358892):

- `P2PNotaryRequestType` payload type is still set to `0x50` (https://github.com/neo-project/neo/pull/2661#discussion_r810020207)
- `P2PNotary` node role is still set to `128` (https://github.com/neo-project/neo/pull/2661#discussion_r810248536 and https://github.com/neo-project/neo/pull/2661#discussion_r880057682).

Speaking of the PR logic:

- Notary deposit withdrawal is performed in two steps (Mint + Burn) (https://github.com/neo-project/neo/pull/2661#discussion_r824504252).

**Comment by roman-khimov** [comment]
> valuable constants:

Yeah, these can be very problematic long-term even though they're trivial to set once and forget. Thanks for raising this once again.

> Notary deposit withdrawal is performed in two steps (Mint + Burn)

I'm sure it can and should be fixed. But it's not critical for long-term compatibility at the same time.

**Pull request merged**
